package es.franl2p;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-27T11:28:47.385+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "ProductosWebServices", 
                  wsdlLocation = "file:/C:/DesarrolloUPO/tui/grailsCxf/src/main/groovy/ProductosServices.wsdl",
                  targetNamespace = "http://franl2p.wordpress.com/") 
public class ProductosWebServices extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://franl2p.wordpress.com/", "ProductosWebServices");
    public final static QName ProductosServicesPort = new QName("http://franl2p.wordpress.com/", "ProductosServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/DesarrolloUPO/tui/grailsCxf/src/main/groovy/ProductosServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductosWebServices.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/DesarrolloUPO/tui/grailsCxf/src/main/groovy/ProductosServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductosWebServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductosWebServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductosWebServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductosWebServices(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductosWebServices(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductosWebServices(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProductosServices
     */
    @WebEndpoint(name = "ProductosServicesPort")
    public ProductosServices getProductosServicesPort() {
        return super.getPort(ProductosServicesPort, ProductosServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductosServices
     */
    @WebEndpoint(name = "ProductosServicesPort")
    public ProductosServices getProductosServicesPort(WebServiceFeature... features) {
        return super.getPort(ProductosServicesPort, ProductosServices.class, features);
    }

}
